name: Build

on:
  push:
    # release pipeline calls build so don't run it twice
    branches-ignore: ["main"]
  pull_request:
  workflow_call:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  docker:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag ghcr.io/podaboutlist/linkfix-for-discord:$(date +%s)
